version: "3.9"

services:
  bbox1:
    image: busybox
    command: dd if=/dev/zero of=/dev/null bs=4096
    volumes:
      - "vol2:/s1"
   
    environment:
      - VERSION=1.0
      - DOCK_HOST=dock01
    depends_on:
      wapp1:
        condition: service_healthy
    
    deploy:
      mode: replicated
      replicas: 2
      limits:
        cpus: '0.30'
        memory: 10M    

  wapp1:
    image: a0z9/dock:wapp.0.5
    ports:
      - "8091:8080"
    environment:
      - DOCK_HOST=WAPP_HOST      
    
    volumes:
      - "wapp_vol:/var/log/wapp"
    healthcheck:
      test: wget -q --spider localhost:8080
      interval: 4s
      timeout: 3s
      retries: 3
    deploy:
      mode: replicated
      replicas: 3

networks:
  net2:

volumes:
  vol2:
  wapp_vol:
