version: "3.9"

services:
  gst1:
    image: docker/getting-started
    ports:
      - "8081:80"
    
    volumes:
      - "vol2:/s1"
      - "/s2"
   
    environment:
      - PROD
      - VERSION=1.0
      - DOCK_HOST=dock01

networks:
  net2:

volumes:
  vol2:

