version: "3.9"

services:
  gst1:
    image: docker/getting-started
    ports:
      - "8081:80"
    
    volumes:
      - "vol2:/s1"
      - "/s2"
   
    environment:
      - PROD
      - VERSION=1.0
      - DOCK_HOST=dock01

  wapp1:
    build: ./wapp
    ports:
      - "8091:8080"
    environment:
      - DOCK_HOST=WAPP_HOST      
    
    volumes:
      - "wapp_vol:/var/log/wapp"

networks:
  net2:

volumes:
  vol2:
  wapp_vol:
