version: "3.9"

services:
  bbox1:
    image: busybox
    
    volumes:
      - "vol2:/s1"
   
    environment:
      - VERSION=1.0
      - DOCK_HOST=dock01
    depends_on:
      wapp1:
        condition: service_healthy


  wapp1:
    build: ./wapp
    ports:
      - "8091:8080"
    environment:
      - DOCK_HOST=WAPP_HOST      
    
    volumes:
      - "wapp_vol:/var/log/wapp"
    healthcheck:
      test: wget -q --spider localhost:8080
      interval: 4s
      timeout: 3s
      retries: 3


networks:
  net2:

volumes:
  vol2:
  wapp_vol:
