version: "3.9"

services:
  gst0:
    image: docker/getting-started
    ports:
      - 8085:80
      - 8086:8080 
    
    environment:
      - VERSION=1.0
      - DOCK_HOST=$HOSTNAME

  gst1: 
    image: docker/getting-started
    ports:
      - 8083:80
      - 8084:8080    
    
    environment:
      - VERSION=2.0
      - DOCK_HOST=$HOSTNAME
    
