version: "3.9"

services:
  mdb:
    build: ./db_scripts

  web:
    build: ./web_scripts
    links: 
      - "mdb:mariadb"
    environment:
      - MDB_USER=root
      - MDB_PASS=pass
      - DOCK_HOST=$HOST_NAME
      - LOG_DIR=/var/log/web2_log

    depends_on: 
      - mdb 
    ports:
      - "8090:8080"
    volumes:
      - web_log:/var/log/web2_log

volumes:
  web_log:

