FROM node:current-alpine

LABEL MAINTAINER=a0z9@rambler.ru
LABEL VERSION=1.0

WORKDIR /var/www/wapp

ENV VERSION 1.0

COPY wapp.js .
EXPOSE 8080

VOLUME /var/log/wapp

ENTRYPOINT ["node", "wapp.js"]

#ENTRYPOINT node wapp.js
#CMD

